# python numpy

In [ ]:
import numpy as np

In [2]:
python_list = [[1,2,3,4,5], [6,8,9,7,10]]
arr = np.array(python_list)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  8,  9,  7, 10]])

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.ones((4,3), dtype = "int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [5]:
np.full((4,3), 5, dtype = "int")

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [6]:
np.eye((4), dtype = "int")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [7]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [8]:
np.logspace(1,10,5,base=2)

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

In [9]:
np.random.randint(0,10,2)

array([2, 1])

In [10]:

arr=np.arange(0,10)
print(arr)
arr.max()
arr.argmax()

[0 1 2 3 4 5 6 7 8 9]


9

In [11]:
arr=np.random.randint(0,100,(4,3))
print(arr)
print(arr.max())
print(arr.argmax())

[[ 2 64 45]
 [17 63 47]
 [27 72 17]
 [52 70 74]]
74
11


In [12]:

import numpy as np
import time
import sys

S = range(1000)
print(sys.getsizeof(5)*len(S))
D = np.arange(1000)
print(D.size*D.itemsize)

28000
4000


In [13]:
arr=np.random.randint(0,100,(4,3))
print(arr)
print(arr.min())
print(arr.argmin())

[[38 90 58]
 [52  7  6]
 [21 24 83]
 [36 40 49]]
6
5
